### ISSUE TITLE
Versioning Issues and Consistency

### ISSUE THREAD

**Issue by alecholmez** [DecipherNow/gm-fabric-go#279]
@dougfort elaborate your concerns

**Comment by dougfort** [comment]
* merge all approved PRs in gm-fabric-go (except discovery)
* merge all approved PRs in gm-fabric-proxy
* reconcile everything until tests run
* tag gm-fabric-go with 0.1.7
* set the constraint in gm-fabric-proxy to  # (Not ```^``` (the default), not ```>=```; the exact version)
```toml
[[constraint]]
 name = "github.com/deciphernow/gm-fabric-go"
 version = "=0.1.7"
```

* tag gm-fabric-proxy with some form of version
* ship it
* Then we must prepare a version of the fabric generator using 0.1.7 and build the homebrew stuff
* also https://github.com/DecipherNow/gm-fabric-templates/pull/58
