### ISSUE TITLE
update config template from environment variables

### ISSUE THREAD

**Issue by dougfort** [DecipherNow/gm-fabric-go#345]
See https://github.com/DecipherNow/gm-proxy/issues/108

This is a function that reads in a config template of the form 
```yaml
zookeeper:
  addrs: 
    - {{.ZkAddrs}}
  announcePath: {{.AnnouncePath}}
  announceHost: {{.AnnounceHost}}
  announcePort: {{.AnnouncePort}}
  usingTLS: {{.UsingTLS}}
  metrics:
    announcePort: {{.MetricsAnnouncePort}}
```

and writes out a file of the form
```yaml
zookeeper:
  addrs:
    - "dashboard:2181"
  announcePath: "/services/example/0.0.1"
  announceHost: ""
  announcePort: 8080
  usingTLS: false
  metrics:
    announcePort: 8081
```

using environment variables like ```ZK_ADDRS="zk:2181:"``` to supply the variable data.
